name: Deploy public via SFTP

on:
  push:
    branches:
      - master
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy public folder via SFTP
        uses: samkirkland/ftp-deploy-action@v4
        with:
          server: sftp://${{ secrets.SFTP_HOST }}:${{ secrets.SFTP_PORT }}
          username: ${{ secrets.SFTP_USER }}
          password: ${{ secrets.SFTP_PASS }}
          local-dir: ./public
          server-dir: ${{ secrets.SFTP_REMOTE_DIR }}/
